### ISSUE TITLE
误报

### ISSUE THREAD

**Issue by hiw0rld** [We5ter/Flerken#3]
/'b'i'n'/'c'a't' /'e't'c'/'p'a's's'w'd       
![image](https://user-images.githubusercontent.com/13991466/59107247-c79cee00-896a-11e9-97fc-cd8416e14753.png)

已经做的很棒了！

**Comment by dirknono** [comment]
Thanks a lot for your commands.

The tricks that only uses ‘ or “ to make a transformation are not covered by flerken for now. This is also explicitly noted in our specifications. We could have added this case but we believe that other detection methods such as command context analysis, father-child process analysis will certainly help to cover this issue. Also when you only look this kind of feature, you will get thousands of false positives, which you might not want to have a look at.

Best regards,
Yao

发自我的 iPhone
